#! /bin/sh

#If refresing BSPWM, remove all previous rules to prevent doubling up
bspc rule -r "*"
killall -9 sxhkd dunst picom xsettingsd mpd

#Startup stuff
dunst &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
# xsettingsd --config=$HOME/.config/xsettingsd &
picom --config $HOME/.config/picom/picom.conf &
# https://github.com/adi1090x/polybar-themes?tab=readme-ov-file
usr/lib/polkit-kde-authentication-agent-1 &
mpd &
bash ~/.config/polybar/launch.sh --docky & #docky,

#Monitor setup
bspc monitor -d I II III IV V VI VII
xrandr -s 1920x1080 &
feh --no-fehbg --bg-fil $HOME/.config/wallpaper/wallpaper.jpg &

#Cursor setup
xsetroot -cursor_name left_ptr &

#Config border and gap
bspc config border_width            4
bspc config window_gap              5
#bspc config top_padding             20 #Add value according to bar height

#Config else
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config single_monocle          false
bspc config focus_follows_pointer   true
bspc config gapless_monocle         true

#Colors
bspc config focused_border_color   "#711c91"
bspc config normal_border_color    "#1a1032"
bspc config active_border_color    "#0abdc6"
bspc config presel_feedback_color  "#fdee00"
bspc config urgent_border_color    "#cc2885"

#Rules for windows
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a Lxappearance state=floating layer=normal center=true
bspc rule -a Galculator state=floating layer=normal center=true
bspc rule -a Xfce4-terminal state=floating layer=normal center=true
bspc rule -a EXAMPLE desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
